global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'spring_app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app_mtd:8080']

